const DATA = [
    {
      id: '1',
      cheese: 3,
      ham: 2,
      ketchup: true,
      quantity: 2,
      state: 'waiting',
    },
    {
      id: '2',
      cheese: 1,
      ham: 1,
      ketchup: false,
      quantity: 1,
      state: 'done',
    },
    {
      id: '3',
      cheese: 3,
      ham: 0,
      ketchup: true,
      quantity: 1,
      state: 'waiting',
    },
    {
      id: '5',
      cheese: 1,
      ham: 1,
      ketchup: false,
      quantity: 1,
      state: 'waiting',
    },
    {
      id: '6',
      cheese: 3,
      ham: 0,
      ketchup: true,
      quantity: 1,
      state: 'done',
    },
    {
      id: '7',
      cheese: 3,
      ham: 2,
      ketchup: true,
      quantity: 2,
      state: 'waiting',
    },
    {
      id: '8',
      cheese: 1,
      ham: 1,
      ketchup: false,
      quantity: 1,
      state: 'waiting',
    },
    {
      id: '9',
      cheese: 3,
      ham: 0,
      ketchup: true,
      quantity: 1,
      state: 'waiting',
    },
];
export default DATA;
